name: weather_app
description: "this is a weather app to show the weather just by search
  for any city in the world and show the weather details of that 
  city and also show the current weather details of that city you live
  in."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  carousel_slider: ^5.1.1
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.4
  geolocator: ^14.0.2
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.1

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo.png 

flutter_icons:
  android: true
  ios: true
  web: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
